packages:
  - converters/node
  - frontend/subgraph-composer
  - frontend/schema-authoring
  - website
  - external/visual-json

overrides:
  diff@>=5.0.0 <5.2.2: ">=5.2.2"
  esbuild@<=0.24.2: ">=0.25.0"
  lodash@>=4.0.0 <=4.17.22: ">=4.17.23"
  ws@>=8.0.0 <8.17.1: ">=8.17.1"
