use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

fn get_jxql_command() -> Command {
    // Attempt to locate the binary generated by cargo
    // This expects that `cargo build` or `cargo test` has already built the binaries
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let bin_path = PathBuf::from(manifest_dir).join("target/debug/jxql");

    if bin_path.exists() {
        Command::new(bin_path)
    } else {
        // Fallback to cargo run (slower, might lock if running concurrent tests)
        let mut cmd = Command::new("cargo");
        cmd.args(&["run", "--bin", "jxql", "--quiet", "--"]);
        cmd.current_dir(manifest_dir);
        cmd
    }
}

#[test]
fn test_help_flag() {
    let output = get_jxql_command()
        .arg("--help")
        .output()
        .expect("Failed to execute jxql");

    assert!(output.status.success());
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("Usage: jxql"));
}

#[test]
fn test_version_flag() {
    let output = get_jxql_command()
        .arg("--version")
        .output()
        .expect("Failed to execute jxql");

    assert!(output.status.success());
}

#[test]
fn test_basic_conversion() {
    let schema = r#"{
        "type": "object",
        "x-graphql-type-name": "Object",
        "properties": {
            "name": { "type": "string" }
        }
    }"#;

    let temp_dir = env::temp_dir();
    let input_file = temp_dir.join("basic_test.json");
    fs::write(&input_file, schema).unwrap();

    let output = get_jxql_command()
        .arg("--input")
        .arg(input_file.to_str().unwrap())
        .output()
        .expect("Failed to execute jxql");

    assert!(
        output.status.success(),
        "Stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("type Object"));
    assert!(stdout.contains("name: String"));
}

#[test]
fn test_infer_ids() {
    let schema = r#"{
        "type": "object",
        "x-graphql-type-name": "TestType",
        "properties": {
            "id": { "type": "string" },
            "other": { "type": "string" }
        }
    }"#;

    let temp_dir = env::temp_dir();
    let input_file = temp_dir.join("infer_ids_test.json");
    fs::write(&input_file, schema).unwrap();

    let output = get_jxql_command()
        .arg("--input")
        .arg(input_file.to_str().unwrap())
        .arg("--infer-ids")
        .output()
        .expect("Failed to execute jxql");

    assert!(output.status.success());
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("id: ID"));
    assert!(stdout.contains("other: String"));
}

#[test]
fn test_write_to_file() {
    let schema = r#"{"type":"object","x-graphql-type-name":"TestType","properties":{"f":{"type":"string"}}}"#;
    let temp_dir = env::temp_dir();
    let input_file = temp_dir.join("output_test_in.json");
    let output_file = temp_dir.join("output_test_out.graphql");
    fs::write(&input_file, schema).unwrap();

    let output = get_jxql_command()
        .arg("--input")
        .arg(input_file.to_str().unwrap())
        .arg("--output")
        .arg(output_file.to_str().unwrap())
        .output()
        .expect("Failed to execute jxql");

    assert!(output.status.success());
    assert!(output_file.exists());

    let content = fs::read_to_string(&output_file).unwrap();
    assert!(content.contains("f: String"));
}

#[test]
fn test_invalid_file() {
    let output = get_jxql_command()
        .arg("--input")
        .arg("non_existent_file_12345.json")
        .output()
        .expect("Failed to execute jxql");

    assert!(!output.status.success());
}
