/**
 * Rust WASM Converter Wrapper
 *
 * Wraps the Rust WASM converter (from converters/rust compiled to WASM)
 * for use in the browser with dynamic loading and fallback handling.
 */

import type {
  ConversionResult,
  ConversionError,
  JsonToGraphQLOptions,
  GraphQLToJsonOptions,
} from "../types";

/**
 * WASM module interface (generated by wasm-pack)
 */
interface WasmModule {
  convert_json_to_sdl: (jsonSchema: string, options: string) => string;
  convert_sdl_to_json: (sdl: string, options: string) => string;
  get_version: () => string;
  validate_json_schema: (jsonSchema: string) => string;
  validate_graphql_sdl: (sdl: string) => string;
}

/**
 * WASM converter state
 */
type WasmState =
  | { status: "uninitialized" }
  | { status: "loading" }
  | { status: "ready"; module: WasmModule }
  | { status: "error"; error: Error };

/**
 * WASM converter configuration
 */
interface WasmConverterConfig {
  wasmPath?: string;
  autoInit?: boolean;
  fallbackToNode?: boolean;
}

/**
 * Default configuration
 */
const DEFAULT_CONFIG: Required<WasmConverterConfig> = {
  wasmPath: "/wasm/json_schema_x_graphql_bg.wasm",
  autoInit: true,
  fallbackToNode: true,
};

/**
 * Rust WASM converter class
 */
export class WasmConverter {
  private config: Required<WasmConverterConfig>;
  private state: WasmState = { status: "uninitialized" };
  private initPromise: Promise<void> | null = null;

  constructor(config: WasmConverterConfig = {}) {
    this.config = { ...DEFAULT_CONFIG, ...config };

    if (this.config.autoInit) {
      this.init().catch((error) => {
        console.error("Failed to auto-initialize WASM converter:", error);
      });
    }
  }

  /**
   * Initialize WASM module
   */
  async init(): Promise<void> {
    // Return existing promise if already initializing
    if (this.initPromise) {
      return this.initPromise;
    }

    // Already initialized
    if (this.state.status === "ready") {
      return;
    }

    // Already failed
    if (this.state.status === "error") {
      throw this.state.error;
    }

    this.state = { status: "loading" };

    this.initPromise = (async () => {
      try {
        // Dynamic import of WASM module
        // This assumes wasm-pack output or similar structure
        let module: WasmModule;

        try {
          // Try to import from the wasm directory
          // Use dynamic import with error handling for missing module
          const wasmModule = await import("@wasm/json_schema_x_graphql").catch(
            () => null,
          );

          if (!wasmModule) {
            throw new Error(
              "WASM module not found at @wasm/json_schema_x_graphql",
            );
          }

          await wasmModule.default();
          module = wasmModule as unknown as WasmModule;
        } catch (error) {
          console.warn(
            "Failed to load WASM from @wasm, trying alternative path:",
            error,
          );

          // Fallback: try to load from public directory
          const response = await fetch(this.config.wasmPath);
          if (!response.ok) {
            throw new Error(`Failed to fetch WASM: ${response.statusText}`);
          }

          const wasmBytes = await response.arrayBuffer();
          const wasmModule = await WebAssembly.instantiate(wasmBytes);
          module = wasmModule.instance.exports as unknown as WasmModule;
        }

        this.state = { status: "ready", module };
        console.info("✓ WASM converter initialized successfully");
      } catch (error) {
        const err =
          error instanceof Error
            ? error
            : new Error("Unknown WASM initialization error");
        this.state = { status: "error", error: err };
        console.warn("✗ WASM converter initialization failed:", err.message);
        console.info("💡 To enable WASM converter, run: pnpm run build:wasm");
        console.info("💡 The app will use Node.js converter as fallback");
        throw err;
      }
    })();

    return this.initPromise;
  }

  /**
   * Ensure WASM is initialized
   */
  private async ensureInitialized(): Promise<WasmModule> {
    // If already ready, return immediately
    const preCheckState = this.state;
    if (preCheckState.status === "ready") {
      return preCheckState.module;
    }

    // If already errored, throw immediately
    if (preCheckState.status === "error") {
      throw new Error(
        "WASM converter failed to initialize: " + preCheckState.error.message,
      );
    }

    // Otherwise, need to initialize
    await this.init();

    // Re-read state after initialization and check again
    // TypeScript can't track state changes through async, so we re-read completely
    const postInitState = this.state;

    if (postInitState.status === "ready") {
      return postInitState.module;
    }

    if (postInitState.status === "error") {
      throw new Error(
        "WASM converter initialization failed: " + postInitState.error.message,
      );
    }

    // If still uninitialized or loading, something went wrong
    throw new Error("WASM converter still not ready after initialization");
  }

  /**
   * Convert JSON Schema to GraphQL SDL
   */
  async convertJsonToGraphQL(
    jsonSchema: string,
    options: JsonToGraphQLOptions = {},
  ): Promise<ConversionResult> {
    const startTime = performance.now();

    try {
      // Validate JSON first
      let parsedSchema: unknown;
      try {
        parsedSchema = JSON.parse(jsonSchema);
      } catch (error) {
        return this.createErrorResult(
          "Invalid JSON Schema: " +
            (error instanceof Error ? error.message : "Parse error"),
          startTime,
          1,
          1,
        );
      }

      const module = await this.ensureInitialized();

      // Prepare options for WASM
      const wasmOptions = {
        include_federation_directives:
          options.includeFederationDirectives ?? false,
        include_schema_link: options.includeSchemaLink ?? false,
        include_descriptions: options.includeDescriptions ?? true,
        custom_scalars: options.customScalars,
        type_prefix: options.typePrefix,
        type_suffix: options.typeSuffix,
        field_name_case: options.fieldNameCase ?? "camelCase",
        enum_case: options.enumCase ?? "UPPER_CASE",
      };

      // Call WASM function
      const resultJson = module.convert_json_to_sdl(
        JSON.stringify(parsedSchema),
        JSON.stringify(wasmOptions),
      );

      const result = JSON.parse(resultJson);
      const duration = performance.now() - startTime;

      if (result.error) {
        return this.createErrorResult(
          result.error.message,
          startTime,
          result.error.line,
          result.error.column,
          result.error.context,
        );
      }

      return {
        success: true,
        output: result.output,
        warnings: result.warnings || [],
        metadata: {
          inputLength: jsonSchema.length,
          outputLength: result.output.length,
          typesGenerated: result.metadata?.types_generated,
          fieldsGenerated: result.metadata?.fields_generated,
          directivesApplied: result.metadata?.directives_applied,
          timestamp: new Date().toISOString(),
        },
        engine: "rust-wasm",
        duration,
      };
    } catch (error) {
      return this.createErrorResult(
        error instanceof Error ? error.message : "Unknown error occurred",
        startTime,
      );
    }
  }

  /**
   * Convert GraphQL SDL to JSON Schema
   */
  async convertGraphQLToJson(
    graphqlSchema: string,
    options: GraphQLToJsonOptions = {},
  ): Promise<ConversionResult> {
    const startTime = performance.now();

    try {
      if (!graphqlSchema.trim()) {
        return this.createErrorResult(
          "GraphQL schema cannot be empty",
          startTime,
        );
      }

      const module = await this.ensureInitialized();

      // Prepare options for WASM
      const wasmOptions = {
        schema_version:
          options.schemaVersion ?? "http://json-schema.org/draft-07/schema#",
        include_descriptions: options.includeDescriptions ?? true,
        include_deprecated: options.includeDeprecated ?? true,
        custom_scalar_mappings: options.customScalarMappings,
      };

      // Call WASM function
      const resultJson = module.convert_sdl_to_json(
        graphqlSchema,
        JSON.stringify(wasmOptions),
      );

      const result = JSON.parse(resultJson);
      const duration = performance.now() - startTime;

      if (result.error) {
        return this.createErrorResult(
          result.error.message,
          startTime,
          result.error.line,
          result.error.column,
          result.error.context,
        );
      }

      return {
        success: true,
        output: result.output,
        warnings: result.warnings || [],
        metadata: {
          inputLength: graphqlSchema.length,
          outputLength: result.output.length,
          timestamp: new Date().toISOString(),
        },
        engine: "rust-wasm",
        duration,
      };
    } catch (error) {
      return this.createErrorResult(
        error instanceof Error ? error.message : "Unknown error occurred",
        startTime,
      );
    }
  }

  /**
   * Validate JSON Schema
   */
  async validateJsonSchema(jsonSchema: string): Promise<{
    valid: boolean;
    errors: Array<{ message: string; path?: string }>;
  }> {
    try {
      const module = await this.ensureInitialized();
      const resultJson = module.validate_json_schema(jsonSchema);
      return JSON.parse(resultJson);
    } catch (error) {
      return {
        valid: false,
        errors: [
          {
            message:
              error instanceof Error ? error.message : "Validation failed",
          },
        ],
      };
    }
  }

  /**
   * Validate GraphQL SDL
   */
  async validateGraphQLSdl(sdl: string): Promise<{
    valid: boolean;
    errors: Array<{ message: string; line?: number; column?: number }>;
  }> {
    try {
      const module = await this.ensureInitialized();
      const resultJson = module.validate_graphql_sdl(sdl);
      return JSON.parse(resultJson);
    } catch (error) {
      return {
        valid: false,
        errors: [
          {
            message:
              error instanceof Error ? error.message : "Validation failed",
          },
        ],
      };
    }
  }

  /**
   * Check if WASM converter is available
   */
  isAvailable(): boolean {
    return this.state.status === "ready";
  }

  /**
   * Check if WASM converter is loading
   */
  isLoading(): boolean {
    return this.state.status === "loading";
  }

  /**
   * Get initialization error if any
   */
  getError(): Error | null {
    return this.state.status === "error" ? this.state.error : null;
  }

  /**
   * Get converter version
   */
  async getVersion(): Promise<string | null> {
    try {
      const module = await this.ensureInitialized();
      return module.get_version();
    } catch {
      return null;
    }
  }

  /**
   * Update configuration
   */
  updateConfig(config: Partial<WasmConverterConfig>): void {
    this.config = { ...this.config, ...config };
  }

  /**
   * Reset and reinitialize
   */
  async reset(): Promise<void> {
    this.state = { status: "uninitialized" };
    this.initPromise = null;
    await this.init();
  }

  /**
   * Create error result helper
   */
  private createErrorResult(
    message: string,
    startTime: number,
    line?: number,
    column?: number,
    context?: string,
  ): ConversionResult {
    const error: ConversionError = {
      message,
      line,
      column,
      context,
      suggestion: this.getSuggestionForError(message),
    };

    return {
      success: false,
      error,
      engine: "rust-wasm",
      duration: performance.now() - startTime,
    };
  }

  /**
   * Get suggestion for common errors
   */
  private getSuggestionForError(message: string): string | undefined {
    if (message.includes("WASM") || message.includes("initialize")) {
      return "Failed to load WASM module. Try refreshing the page or check browser compatibility.";
    }
    if (message.includes("Invalid JSON")) {
      return "Check your JSON syntax. Common issues: trailing commas, unquoted keys, single quotes instead of double quotes.";
    }
    if (message.includes("empty")) {
      return "Provide a valid schema with at least one type definition.";
    }
    if (message.includes("parse")) {
      return "The schema contains syntax errors. Check the error location and fix the syntax.";
    }
    if (message.includes("type")) {
      return "Type mismatch detected. Ensure all types are properly defined and referenced.";
    }
    if (message.includes("federation")) {
      return "Federation directive error. Ensure you have enabled federation directives and they are correctly applied.";
    }
    return undefined;
  }
}

/**
 * Create and export singleton instance
 */
export const wasmConverter = new WasmConverter();

/**
 * Re-export for convenience
 */
export default WasmConverter;
